### ISSUE TITLE
How to reuse Vuetify's variables?

### ISSUE THREAD

**Issue by f-lawe** [vuetifyjs/vuetify-loader#344]
Hi there,

[Documentation](https://github.com/vuetifyjs/vuetify-loader/tree/master/packages/vite-plugin) says:
```
 settings.scss can be used in your own components to access vuetify's variables.
```

But it doesn't say how. I tried this, but I got `[sass] Error: Undefined variable`:
```scss
@use "./settings";

.my-div {
  background-color: settings.$button-background;
}
```

What am I missing?

Happy to share any information needed!
